on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN || github.token }}
          release-type: node

  build:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install dependencies [linux]
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update

          # for build rpm in ubuntu ( https://stackoverflow.com/questions/59346604/electron-forge-make-wont-build )
          sudo apt install -y rpm

      - name: Install NPM dependencies
        run: |
          npm install --global yarn
          yarn install

      - name: Build artifacts
        run: yarn run build

      - name: Prepare artifacts [linux]
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p build
          cp packages/userscript/dist/script.min.user.js build/
          cp packages/app/out/make/deb/x64/*.deb build/
          cp packages/app/out/make/rpm/x64/*.rpm build/

      - name: Upload artifacts [linux]
        if: matrix.os == 'ubuntu-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN || github.token }}
        run: |
          tar -czvf digdig.io-tools-linux-x64.tar.gz -C build .
          gh release upload ${{ needs.release-please.outputs.tag_name }} digdig.io-tools-linux-x64.tar.gz

      - name: Prepare artifacts [macos]
        if: matrix.os == 'macos-latest'
        run: |
          mkdir -p build
          cp packages/userscript/dist/script.min.user.js build/
          cp packages/app/out/make/zip/darwin/arm64/*.zip build/

      - name: Upload artifacts [macos]
        if: matrix.os == 'macos-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN || github.token }}
        run: |
          tar -czvf digdig.io-tools-macos-arm64.tar.gz -C build .
          gh release upload ${{ needs.release-please.outputs.tag_name }} digdig.io-tools-macos-arm64.tar.gz

      - name: Prepare artifacts [windows]
        if: matrix.os == 'windows-latest'
        run: |
          New-Item -Path build -ItemType Directory
          Copy-Item packages\userscript\dist\script.min.user.js build\
          Copy-Item packages\app\out\make\squirrel.windows\x64\*.exe build\

      - name: Upload artifacts [windows]
        if: matrix.os == 'windows-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN || github.token }}
        run: |
          Compress-Archive -Path build -DestinationPath digdig.io-tools-windows-x64.zip
          gh release upload ${{ needs.release-please.outputs.tag_name }} digdig.io-tools-windows-x64.zip
